apiVersion: apps/v1
kind: Deployment
metadata:
  name:  music-service
  labels:
    app: music-service
spec:
  selector:
    matchLabels:
      app: music-service
  replicas: 3
  template:
    metadata:
      labels:
        app:  music-service
    spec:
      containers:
        - name:  music-service
          image: localhost:5000/music-service
          imagePullPolicy: Always
          ports:
            - containerPort:  90

---

apiVersion: v1
kind: Service
metadata:
  name: music-service
spec:
  selector:
    app: music-service
  type: NodePort
  ports:
    - port: 80
      targetPort: 90
      protocol: TCP